env:
  classname:          marl_factory_grid.environment.configs.marl_eval
  env_name:           "marl_eval/dirt_quadrant_eval_config"
  n_agents:           2 # Number of agents in the environment
  eval_render:        True # If inference should be graphically visualized
  save_and_log:       False # If configurations and potential logging files should be saved
algorithm:
  pile-order:         "smart" # Triggers implementation of our emergence prevention mechanism. Agents consider distance to other agent
  pile-observability: "single" # Agents can only perceive one dirt pile at any given time step
  pile_all_done:      "shared" # Indicates that agents don't have to collect the same dirt piles
  auxiliary_piles:    False # Dirt quadrant does not use this option
