env:
  classname:          marl_factory_grid.configs.marl.single_agent_configs
  env_name:           "marl/single_agent_configs/coin_quadrant_agent1_eval_config"
  n_agents:           1 # Number of agents in the environment
  eval_render:        True # If inference should be graphically visualized
  save_and_log:       False # If configurations and potential logging files should be saved
algorithm:
  seed:               42 # Picks seed to make random parts of algorithm reproducible. -1 for random seed
  pile-order:         "fixed" # Clean coin piles in a fixed order specified by the environment config (cf. coords_or_quantity)
  pile-observability: "single" # Agent can only perceive one coin pile at any given time step
  pile_all_done:      "all" # During inference the episode ends only when all coin piles are cleaned
  auxiliary_piles:    False # Coin quadrant does not use this option

