General:
  # RNG-seed to sample the same "random" numbers every time, to make the different runs comparable.
  env_seed: 69
  # Individual vs global rewards
  individual_rewards: true
  # The level.txt file to load from marl_factory_grid/levels
  level_name: two_rooms
  # View Radius
  pomdp_r: 0 # Use custom partial observability setting
  # Print all messages and events
  verbose: false
  # Run tests
  tests: false

# Define Agents, their actions, observations and spawnpoints
Agents:
  Agent2:
    Actions:
      - Move4
      - DoorUse
    Observations:
      - DirtPiles
      - Self
    Positions: # Each spawnpoint is mapped to one dirt pile looping over coords_or_quantity (see below)
      - (3,13)
      - (2,13) # spawnpoint only required if agent2 should go to its auxiliary pile

Entities:
  DirtPiles:
    coords_or_quantity: (2,13), (3,2)  # Locations of dirt piles
    initial_amount: 0.5
    clean_amount: 1
    dirt_spawn_r_var: 0
    max_global_amount: 12
    max_local_amount: 1

  Doors: { }

# Rules section specifies the rules governing the dynamics of the environment.
Rules:
  # Utilities
  # This rule defines the collision mechanic, introduces a related DoneCondition and lets you specify rewards.
  WatchCollisions:
    done_at_collisions: false

  # Done Conditions
  # Define the conditions for the environment to stop. Either success or a fail conditions
  # Environment execution stops after 30 steps
  DoneAtMaxStepsReached:
    max_steps: 30
